### ISSUE TITLE
Lua functions

### ISSUE THREAD

**Issue by madonuko** [rpm-rs/rpmspec-rs#3]
For a detailed list of Lua functions, check out the [RPM manual](https://rpm-software-management.github.io/rpm/manual/lua.html).

## Tasks
- [x] Finish Lua RPM Extension
- [x] Finish Lua Posix Extension
- [x] Finish Lua REPL
- [ ] #6
